// Generated by precompute_agent_run.py. Do not edit by hand.
window.AGENT_RUN = {
  "source": "the agent, deterministic keyword extractor, eval dataset of 8 synthetic documents",
  "admitted": [
    "CON-001",
    "LTR-001",
    "LTR-002",
    "LTR-003",
    "MIN-004",
    "RPT-005",
    "LTR-006"
  ],
  "refused": [
    "LTR-OOS-1"
  ],
  "events": [
    {
      "event_id": "evt-LTR-001-differing_site_conditions",
      "event_type": "differing_site_conditions",
      "clause": "GC 4.12",
      "confidence": 0.92,
      "surfaced": true,
      "citations": [
        {
          "doc_id": "LTR-001",
          "quote": "differing site conditions",
          "verified": true
        }
      ]
    },
    {
      "event_id": "evt-LTR-002-delay",
      "event_type": "delay",
      "clause": "GC 8.4",
      "confidence": 0.88,
      "surfaced": true,
      "citations": [
        {
          "doc_id": "LTR-002",
          "quote": "delay to the critical path",
          "verified": true
        }
      ]
    },
    {
      "event_id": "evt-LTR-003-scope_change",
      "event_type": "scope_change",
      "clause": "GC 13.1",
      "confidence": 0.9,
      "surfaced": true,
      "citations": [
        {
          "doc_id": "LTR-003",
          "quote": "instruction to add",
          "verified": true
        }
      ]
    },
    {
      "event_id": "evt-MIN-004-watch_item",
      "event_type": "watch_item",
      "clause": null,
      "confidence": 0.35,
      "surfaced": false,
      "citations": [
        {
          "doc_id": "MIN-004",
          "quote": "possible resequencing",
          "verified": true
        }
      ]
    },
    {
      "event_id": "evt-RPT-005-delay",
      "event_type": "delay",
      "clause": "GC 8.4",
      "confidence": 0.55,
      "surfaced": false,
      "citations": [
        {
          "doc_id": "RPT-005",
          "quote": "behind schedule",
          "verified": true
        }
      ]
    }
  ],
  "deadlines": [
    {
      "event_id": "evt-LTR-001-differing_site_conditions",
      "clause": "GC 4.12",
      "trigger_date": "2026-08-01",
      "deadline_date": "2026-08-29",
      "provisional": false,
      "reason": "computed from contract notice period"
    },
    {
      "event_id": "evt-LTR-002-delay",
      "clause": "GC 8.4",
      "trigger_date": "2026-08-05",
      "deadline_date": "2026-09-02",
      "provisional": false,
      "reason": "computed from contract notice period"
    },
    {
      "event_id": "evt-LTR-003-scope_change",
      "clause": "GC 13.1",
      "trigger_date": "2026-08-10",
      "deadline_date": "2026-08-24",
      "provisional": true,
      "reason": "amendment AMD-3 referenced but missing from archive; deadline provisional"
    }
  ],
  "notices": [
    {
      "notice_id": "ntc-evt-LTR-001-differing_site_conditions",
      "status": "PENDING_APPROVAL"
    },
    {
      "notice_id": "ntc-evt-LTR-002-delay",
      "status": "PENDING_APPROVAL"
    },
    {
      "notice_id": "ntc-evt-LTR-003-scope_change",
      "status": "PENDING_APPROVAL"
    }
  ],
  "golden_missed": [
    [
      "LTR-006",
      "delay"
    ]
  ]
};
